apiVersion: v1
kind: Pod
metadata:
  name: webserver-v3
  labels:
    app: nginxweb
    type: production
    ver: v3
spec:
  containers:
  - name: web
    image: akhileshaca/nginx-alpine:v3
    ports:
    - containerPort: 80
