apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: ws-deployment
spec:  
  selector:
    matchLabels:
      app: nginxweb
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxweb
    spec:
      containers:
      - name: web
        image: nginx:1.21.5-alpine
        ports:
        - containerPort: 80
